dist: bionic
sudo: required
language: minimal
env:
  global:
    - ALPINE_VERSION="3.11.6"
    - S6_VERSION=""
    - IMG_NAME="xpecex/alpine-s6"
    - IMG_TAG="$ALPINE_VERSION"
    - DOCKER_CLI_EXPERIMENTAL="enabled"
before_install:
  - sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add 
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
  - sudo apt update
  - sudo apt install -y docker-ce
  - docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
install:
  - docker buildx create --use --name xbuild
script: bash build.sh

