dist: bionic
sudo: required
language: shell
services:
  - docker
env:
  global:
    - S6_VERSION="2.0.0.1"
    - DOCKER_CLI_EXPERIMENTAL="enabled"
    - DOCKER_BUILDKIT=1
addons:
  apt:
    packages:
      - docker-ce
      - docker-ce-cli 
      - containerd.io
install:
  - sudo docker buildx create --use --name qemu
  - sudo docker buildx inspect --bootstrap
script: 
  - ./build-test.sh
